import "./css/style.css";

import { Inter } from "next/font/google";
import localFont from "next/font/local";

import Header from "@/components/general/header";

const financier = localFont({
  src: [
    {
      path: "./css/font/test-financier-display-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./css/font/test-financier-display-regular-italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "./css/font/test-financier-display-bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "././css/font/test-financier-display-bold-italic.woff2",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-financier",
});

const montreal = localFont({
  src: [
    {
      path: "./css/font/NeueMontreal-Bold.otf",
      weight: "700",
      style: "normal",
    },

    {
      path: "./css/font/NeueMontreal-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./css/font/NeueMontreal-Regular.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-montreal",
});

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
//   display: "swap",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${financier.variable} ${montreal.variable} font-financier antialiased bg-gray-500 text-gray-900 tracking-tight`}
      >
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
